### ISSUE TITLE
kotlin-reactive/beer-catalog-service doesn't start w/o MongoDB configured

### ISSUE THREAD

**Issue by mraible** [mraible/cloud-native-pwas#8]
On startup, the following message is printed to the console:

```
2017-11-04 10:56:00.724  INFO 73483 --- [localhost:27017] org.mongodb.driver.cluster               : 
Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.AsynchronousSocketChannelStream$OpenCompletionHandler
        .failed(AsynchronousSocketChannelStream.java:254) ~[mongodb-driver-core-3.5.0.jar:na]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128) ~[na:1.8.0_144]
	at sun.nio.ch.Invoker$2.run(Invoker.java:218) ~[na:1.8.0_144]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_144]
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252) ~[na:1.8.0_144]
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198) ~[na:1.8.0_144]
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213) ~[na:1.8.0_144]
	at sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:301) ~[na:1.8.0_144]
	... 1 common frames omitted
```

I was able to fix it by following the steps in this article:

https://dzone.com/articles/spring-boot-with-embedded-mongodb

Add dependencies to `pom.xml`:

```xml
<dependency>
	<groupId>de.flapdoodle.embed</groupId>
	<artifactId>de.flapdoodle.embed.mongo</artifactId>
	<version>1.50.5</version>
</dependency>
<dependency>
	<groupId>cz.jirutka.spring</groupId>
	<artifactId>embedmongo-spring</artifactId>
	<version>RELEASE</version>
</dependency>
```

Create a `src/main/kotlin/com/example/beercatalogservice/MongoConfig.kt` class:

```kotlin
package com.example.beercatalogservice

import java.io.IOException

import cz.jirutka.spring.embedmongo.EmbeddedMongoFactoryBean
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.data.mongodb.core.*

@Configuration
class MongoConfig {
    @Bean
    @Throws(IOException::class)
    fun mongoTemplate(): MongoTemplate {
        val mongo = EmbeddedMongoFactoryBean()
        mongo.setBindIp(MONGO_DB_URL)
        val mongoClient = mongo.getObject()
        return MongoTemplate(mongoClient, MONGO_DB_NAME)
    }

    companion object {
        private val MONGO_DB_URL = "localhost"
        private val MONGO_DB_NAME = "embeded_db"
    }
}
```

**Comment by mraible** [comment]
Added embedded MongoDB, works on CF.
